### ISSUE TITLE
Add to Travis-CI

### ISSUE THREAD

**Issue by athanclark** [purescript-contrib/purescript-uint#11]
@zaquest Hey there, I was going to add this library to Travis-CI, but I don't have sufficient rights to do so. I think this ought to be consistently monitored; it's such a fundamental concept, I'd hate to see it go incompatible as time goes on.

Thanks!

**Comment by zaquest** [comment]
Hello. Added to travis-ci and [commited](https://github.com/zaquest/purescript-uint/commit/545bbf00e3eeabad5f5f62f393a18ec8373feffd) build status badge to readme. Let me know if you need anything else.

**Comment by athanclark** [comment]
Thank you!
