### ISSUE TITLE
Missing Generics-Rep dependency

### ISSUE THREAD

**Issue by justinwoo** [purescript-contrib/purescript-uint#9]
Please add this dependency to your bower.json and publish a patch release, as you have undeclared Generics-Rep usages. You can prevent this problem in the future by adding dev dependencies to your dependencies or using `bower i -p` (production install) to see if `pulp build` will succeed.

**Comment by justinwoo** [comment]
https://github.com/zaquest/purescript-uint/blob/25a52763e94fd6481348cbee55ba87737e0fbd70/src/Data/UInt.purs#L42

**Comment by athanclark** [comment]
Definitely! Thank you for the heads up. Is this a compiler bug? Because it compiles fine currently, as of purs v0.12.0

**Comment by athanclark** [comment]
er, derp, sorry I just kinda lapsed in what I was reading. Sorry, got the bower dependencies fixed!
